"""empty message

Revision ID: 32a5bab42e14
Revises: 
Create Date: 2020-10-20 18:53:38.516522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32a5bab42e14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_agent',
    sa.Column('uuid', sa.String(length=64), nullable=False),
    sa.Column('capability', sa.String(length=64), nullable=True),
    sa.Column('capability_code', sa.String(length=32), nullable=True),
    sa.Column('ipv4address', sa.String(length=32), nullable=True),
    sa.Column('ipv4port', sa.String(length=8), nullable=True),
    sa.Column('node_uuid', sa.String(length=64), nullable=False),
    sa.Column('start_dt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_dt', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('tb_bios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_uuid', sa.String(length=64), nullable=True),
    sa.Column('bios_version', sa.String(length=128), nullable=True),
    sa.Column('firmware_version', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_bios_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_uuid', sa.String(length=64), nullable=True),
    sa.Column('bios_id', sa.Integer(), nullable=True),
    sa.Column('isdefault', sa.Integer(), nullable=False),
    sa.Column('iscurrent', sa.Integer(), nullable=False),
    sa.Column('config_list_id', sa.Integer(), nullable=True),
    sa.Column('register_dt', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_bios_config_avail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('avail_list_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('key_id', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_bios_config_avail_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_cnt', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_bios_config_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_cnt', sa.Integer(), nullable=False),
    sa.Column('register_dt', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_bios_config_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_list_id', sa.Integer(), nullable=True),
    sa.Column('section_key', sa.String(length=256), nullable=False),
    sa.Column('key', sa.String(length=256), nullable=True),
    sa.Column('value', sa.String(length=256), nullable=True),
    sa.Column('viewtype', sa.String(length=32), nullable=True),
    sa.Column('avail_list_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_bios_hist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bios_id', sa.Integer(), nullable=True),
    sa.Column('node_uuid', sa.String(length=64), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('kind_code', sa.String(length=32), nullable=True),
    sa.Column('bios_version', sa.String(length=128), nullable=True),
    sa.Column('firmware_version', sa.String(length=32), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=True),
    sa.Column('result_code', sa.String(length=32), nullable=True),
    sa.Column('error', sa.String(length=256), nullable=True),
    sa.Column('error_code', sa.String(length=32), nullable=True),
    sa.Column('register_dt', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_firmware_depandency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('fw_type', sa.String(length=32), nullable=True),
    sa.Column('fw_type_code', sa.String(length=32), nullable=True),
    sa.Column('fw_version', sa.String(length=64), nullable=True),
    sa.Column('register_dt', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_firmware_depandency_hw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=256), nullable=True),
    sa.Column('product_code', sa.String(length=64), nullable=True),
    sa.Column('vendor', sa.String(length=64), nullable=True),
    sa.Column('register_dt', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_firmware_hist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_uuid', sa.String(length=64), nullable=True),
    sa.Column('fw_type', sa.String(length=32), nullable=True),
    sa.Column('fw_type_code', sa.String(length=32), nullable=True),
    sa.Column('fw_version', sa.String(length=64), nullable=True),
    sa.Column('product_name', sa.String(length=256), nullable=True),
    sa.Column('product_code', sa.String(length=64), nullable=True),
    sa.Column('vendor', sa.String(length=64), nullable=True),
    sa.Column('release_day', sa.String(length=32), nullable=True),
    sa.Column('package_kind', sa.String(length=32), nullable=True),
    sa.Column('package_kind_code', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=True),
    sa.Column('action_code', sa.String(length=32), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=True),
    sa.Column('result_code', sa.String(length=32), nullable=True),
    sa.Column('error', sa.String(length=256), nullable=True),
    sa.Column('error_code', sa.String(length=32), nullable=True),
    sa.Column('register_dt', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_firmware_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bios_id', sa.Integer(), nullable=True),
    sa.Column('fw_file_name', sa.String(length=128), nullable=True),
    sa.Column('fw_file_path', sa.String(length=256), nullable=True),
    sa.Column('fw_type', sa.String(length=32), nullable=True),
    sa.Column('fw_type_code', sa.String(length=32), nullable=True),
    sa.Column('fw_version', sa.String(length=64), nullable=True),
    sa.Column('product_name', sa.String(length=256), nullable=True),
    sa.Column('product_code', sa.String(length=64), nullable=True),
    sa.Column('vendor', sa.String(length=64), nullable=True),
    sa.Column('release_day', sa.String(length=32), nullable=True),
    sa.Column('package_kind', sa.String(length=32), nullable=True),
    sa.Column('package_kind_code', sa.String(length=32), nullable=True),
    sa.Column('register_dt', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_ipmi_connect_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ipv4address', sa.String(length=32), nullable=True),
    sa.Column('ipv4port', sa.String(length=16), nullable=True),
    sa.Column('users', sa.String(length=32), nullable=True),
    sa.Column('passwd', sa.String(length=256), nullable=True),
    sa.Column('node_uuid', sa.String(length=64), nullable=True),
    sa.Column('is_discovery', sa.Integer(), nullable=True),
    sa.Column('register_dt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update_dt', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_ipmi_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=32), nullable=True),
    sa.Column('event_day', sa.String(length=128), nullable=True),
    sa.Column('event_time', sa.String(length=128), nullable=True),
    sa.Column('sensor_type', sa.String(length=64), nullable=True),
    sa.Column('sensor_divice_code', sa.String(length=8), nullable=True),
    sa.Column('sensor_event', sa.String(length=64), nullable=True),
    sa.Column('sensor_evnet_result', sa.String(length=32), nullable=True),
    sa.Column('register_dt', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_ipmi_sdrtype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sdr_type_name', sa.String(length=128), nullable=True),
    sa.Column('sdr_type_code', sa.String(length=128), nullable=True),
    sa.Column('sensor_name', sa.String(length=128), nullable=True),
    sa.Column('sensor_divice_code', sa.String(length=8), nullable=True),
    sa.Column('register_dt', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_ipmi_sensor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_name', sa.String(length=128), nullable=True),
    sa.Column('sensor_value', sa.String(length=128), nullable=True),
    sa.Column('sensor_units', sa.String(length=128), nullable=True),
    sa.Column('sensor_state', sa.String(length=64), nullable=True),
    sa.Column('sensor_lo_norec', sa.String(length=128), nullable=True),
    sa.Column('sensor_lo_crit', sa.String(length=128), nullable=True),
    sa.Column('sensor_lo_nocrit', sa.String(length=128), nullable=True),
    sa.Column('sensor_up_nocrit', sa.String(length=128), nullable=True),
    sa.Column('sensor_up_crit', sa.String(length=128), nullable=True),
    sa.Column('sensor_up_norec', sa.String(length=128), nullable=True),
    sa.Column('register_dt', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_node',
    sa.Column('uuid', sa.String(length=64), nullable=False),
    sa.Column('parent_uuid', sa.String(length=64), nullable=True),
    sa.Column('ischild', sa.Integer(), nullable=False),
    sa.Column('node_detail_id', sa.Integer(), nullable=True),
    sa.Column('system_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('tb_node_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capability', sa.String(length=32), nullable=True),
    sa.Column('capability_code', sa.String(length=32), nullable=True),
    sa.Column('alias', sa.String(length=32), nullable=True),
    sa.Column('register_dt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_flag', sa.Integer(), nullable=True),
    sa.Column('is_monitor', sa.Integer(), nullable=True),
    sa.Column('node_uuid', sa.String(length=64), nullable=True),
    sa.Column('note', sa.String(length=256), nullable=True),
    sa.Column('ipmi_conn_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_pxeboot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ismount', sa.Integer(), nullable=True),
    sa.Column('isdefault', sa.Integer(), nullable=True),
    sa.Column('mount_path', sa.String(length=256), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_pxeboot_hist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('os_type', sa.String(length=32), nullable=True),
    sa.Column('os_type_code', sa.String(length=32), nullable=True),
    sa.Column('os_version', sa.String(length=32), nullable=True),
    sa.Column('os_arch', sa.String(length=32), nullable=True),
    sa.Column('os_arch_code', sa.String(length=32), nullable=True),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('target', sa.String(length=32), nullable=True),
    sa.Column('target_code', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=True),
    sa.Column('action_code', sa.String(length=32), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=True),
    sa.Column('result_code', sa.String(length=32), nullable=True),
    sa.Column('error', sa.String(length=256), nullable=True),
    sa.Column('error_code', sa.String(length=32), nullable=True),
    sa.Column('register_dt', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_pxeboot_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('os_type', sa.String(length=32), nullable=True),
    sa.Column('os_type_code', sa.String(length=32), nullable=True),
    sa.Column('os_version', sa.String(length=32), nullable=True),
    sa.Column('os_arch', sa.String(length=32), nullable=True),
    sa.Column('os_arch_code', sa.String(length=32), nullable=True),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('repo_name', sa.String(length=256), nullable=True),
    sa.Column('vmlinuz_path', sa.String(length=256), nullable=True),
    sa.Column('initrd_path', sa.String(length=256), nullable=True),
    sa.Column('image_file_path', sa.String(length=256), nullable=True),
    sa.Column('image_file_name', sa.String(length=256), nullable=True),
    sa.Column('target', sa.String(length=32), nullable=True),
    sa.Column('target_code', sa.String(length=32), nullable=True),
    sa.Column('register_dt', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_system',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_uuid', sa.String(length=64), nullable=True),
    sa.Column('meta_id', sa.Integer(), nullable=True),
    sa.Column('ipv4address', sa.String(length=64), nullable=True),
    sa.Column('os_type', sa.String(length=32), nullable=True),
    sa.Column('os_type_code', sa.String(length=32), nullable=True),
    sa.Column('os_name', sa.String(length=32), nullable=True),
    sa.Column('os_version', sa.String(length=32), nullable=True),
    sa.Column('os_arch', sa.String(length=32), nullable=True),
    sa.Column('os_arch_code', sa.String(length=32), nullable=True),
    sa.Column('kernel_version', sa.String(length=32), nullable=True),
    sa.Column('hostname', sa.String(length=32), nullable=True),
    sa.Column('register_dt', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_system_backup_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meta_id', sa.Integer(), nullable=True),
    sa.Column('image_kind', sa.String(length=32), nullable=False),
    sa.Column('image_kind_code', sa.String(length=32), nullable=True),
    sa.Column('image_hash', sa.String(length=256), nullable=False),
    sa.Column('image_name', sa.String(length=128), nullable=False),
    sa.Column('image_size', sa.String(length=64), nullable=True),
    sa.Column('image_path', sa.String(length=256), nullable=False),
    sa.Column('register_dt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_system_backup_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=True),
    sa.Column('backup_kind', sa.String(length=32), nullable=False),
    sa.Column('backup_kind_code', sa.String(length=32), nullable=True),
    sa.Column('zfs_mount_point', sa.String(length=256), nullable=True),
    sa.Column('image_name', sa.String(length=128), nullable=True),
    sa.Column('zfs_name', sa.String(length=256), nullable=True),
    sa.Column('zfs_used_size', sa.String(length=64), nullable=True),
    sa.Column('zfs_avail_size', sa.String(length=64), nullable=True),
    sa.Column('register_dt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_system_disk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=True),
    sa.Column('disk_used', sa.String(length=64), nullable=True),
    sa.Column('disk_free', sa.String(length=64), nullable=True),
    sa.Column('disk_avail', sa.String(length=64), nullable=True),
    sa.Column('register_dt', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_system_hist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_uuid', sa.String(length=64), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('kind_code', sa.String(length=32), nullable=True),
    sa.Column('backup_kind', sa.String(length=32), nullable=False),
    sa.Column('backup_kind_code', sa.String(length=32), nullable=True),
    sa.Column('zfs_mount_point', sa.String(length=256), nullable=True),
    sa.Column('image_name', sa.String(length=128), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=True),
    sa.Column('result_code', sa.String(length=32), nullable=True),
    sa.Column('register_dt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.String(length=256), nullable=True),
    sa.Column('error_code', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_system_property_zfs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset', sa.String(length=64), nullable=False),
    sa.Column('property', sa.String(length=32), nullable=False),
    sa.Column('value', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_system_zfs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=True),
    sa.Column('zfs_used_size', sa.String(length=64), nullable=True),
    sa.Column('zfs_avail_size', sa.String(length=64), nullable=True),
    sa.Column('zfs_mount_point', sa.String(length=256), nullable=True),
    sa.Column('zfs_name', sa.String(length=256), nullable=True),
    sa.Column('register_dt', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_system_zfs')
    op.drop_table('tb_system_property_zfs')
    op.drop_table('tb_system_hist')
    op.drop_table('tb_system_disk')
    op.drop_table('tb_system_backup_meta')
    op.drop_table('tb_system_backup_image')
    op.drop_table('tb_system')
    op.drop_table('tb_pxeboot_image')
    op.drop_table('tb_pxeboot_hist')
    op.drop_table('tb_pxeboot')
    op.drop_table('tb_node_detail')
    op.drop_table('tb_node')
    op.drop_table('tb_ipmi_sensor')
    op.drop_table('tb_ipmi_sdrtype')
    op.drop_table('tb_ipmi_event')
    op.drop_table('tb_ipmi_connect_info')
    op.drop_table('tb_firmware_image')
    op.drop_table('tb_firmware_hist')
    op.drop_table('tb_firmware_depandency_hw')
    op.drop_table('tb_firmware_depandency')
    op.drop_table('tb_bios_hist')
    op.drop_table('tb_bios_config_options')
    op.drop_table('tb_bios_config_list')
    op.drop_table('tb_bios_config_avail_list')
    op.drop_table('tb_bios_config_avail')
    op.drop_table('tb_bios_config')
    op.drop_table('tb_bios')
    op.drop_table('tb_agent')
    # ### end Alembic commands ###
